Declare offering delivery method and unit.
ps-resources/es-offerings-site-feed pull request #17
Opened 2023-09-18 14:56 UTC by igwejk

This change should facilitate implementation of automations that consumes the offering feed e.g. scoping enhancement https://github.com/github/services/pull/19929

2023-09-18 15:01 UTC, umatty approved these changes

2023-09-18 15:04 UTC, stoe commented
I converted to _draft_ for now, to not send wrong signal before we have discussed and confirmed that the proposed change will not break `github/github`

2023-09-18 15:14 UTC, stoe requested changes

2023-09-18 15:14 UTC, stoe commented on _offerings/offering-ghas-security-advisory-services.md
> +  method: "A minimum committed hours of 4 hours per week; committed hours may be more based on contract duration."
```suggestion
  method: "A minimum commitment of 4 hours per week; committed hours may be more based on contract duration."
```

2023-09-18 15:14 UTC, stoe commented on _offerings/offering-technical-advisory-services.md
> +  method: "A minimum committed hours of 4 hours per week; committed hours may be more based on contract duration."
```suggestion
  method: "A minimum commitment of 4 hours per week; committed hours may be more based on contract duration."
```

2023-09-19 04:58 UTC, stoe commented
@igwejk, do think we could add a test to https://github.com/github/github/blob/master/test/lib/explore_feed/professional_service_test.rb to ensure the additional fields get ignored?

2023-09-19 05:45 UTC, stoe reviewed
Visual nit-pick on the rendered MD...
I think the `delivery` section should be at the end of the rendered MD, after `parameterized_name`.

But maybe that's just me ¯\_(ツ)_/¯

![image](https://github.com/ps-resources/es-offerings-site-feed/assets/203805/998a4a1d-986d-4365-8a95-606a0b1c9133)

2023-09-19 06:40 UTC, stoe approved these changes

2023-09-19 07:20 UTC, merged